apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels:
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    type: {{ .Chart.Name }}
    app: {{ .Release.Name }}
    {{- if .Values.metadata.labels.datadog.env }}	
    tags.datadoghq.com/env: {{ .Values.metadata.labels.datadog.env }}
    {{- end }}
    {{- if .Values.metadata.labels.datadog.env }}	
    tags.datadoghq.com/service: {{ .Values.metadata.labels.datadog.env }}
    {{- end }}
    {{- if .Values.metadata.labels.datadog.service }}	
    tags.datadoghq.com/version: {{ .Values.metadata.labels.datadog.version }}
    {{- end }}
spec:
  replicas: {{ .Values.scale.minReplicas }}
  selector:
    matchLabels:
      type: {{ .Chart.Name }}
      app: {{ .Release.Name }}
  template:
    metadata:
      labels:
        type: {{ .Chart.Name }}
        app: {{ .Release.Name }}
        {{- if .Values.metadata.labels.datadog }}	
        tags.datadoghq.com/env: {{ .Values.metadata.labels.datadog.env }}	
        tags.datadoghq.com/service: {{ .Values.metadata.labels.datadog.service }}	
        tags.datadoghq.com/version: {{ .Values.metadata.labels.datadog.version }}	
        {{- end }}
    spec:
      {{- if .Values.aws_iam_role_arn }}	
      serviceAccountName: {{ .Release.Name }}	
      securityContext:	
        fsGroup: 65534 # To be able to read Kubernetes and AWS token files	
      {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.image_repo }}:{{ .Values.image_tag }}"
          imagePullPolicy: {{ .Values.image_pull_policy }}
          {{- if .Values.command }}
          command:
            {{- .Values.command | toYaml | nindent 12 }}
          {{- end }}
          {{- if .Values.args }}
          args:
            {{- .Values.args | toYaml | nindent 12 }}
          {{- end }}
          env:
            - name: PORT
              value: {{ .Values.port | quote  }}
          {{- if .Values.env }}
          {{- range $key, $val := .Values.env }}
            - name: {{ $key }}
              value: {{ $val | quote }}
          {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.port }}
              protocol: TCP
          {{- if .Values.probe.liveness }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probe.liveness | quote }}
              port: http
            initialDelaySeconds: {{ .Values.probe.livenessInitialDelaySeconds }}
            periodSeconds: {{ .Values.probe.livenessPeriodSeconds }}
          {{- end }}
          {{- if .Values.probe.readiness }}
          readinessProbe:
            httpGet:
              path: {{ .Values.probe.readiness | quote }}
              port: http
            initialDelaySeconds: {{ .Values.probe.readinessInitialDelaySeconds }}
            periodSeconds: {{ .Values.probe.readinessPeriodSeconds }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
